/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonRaspberryPiPico2W.description': 'A wireless variant of the Raspberry Pi Pico 2 powered by the RP2350 with onboard Wi-Fi and Bluetooth.',
            'microPythonRaspberryPiPico2W.examples.blink.name': 'Blink',
            'microPythonRaspberryPiPico2W.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonRaspberryPiPico2W.examples.button.name': 'Button',
            'microPythonRaspberryPiPico2W.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonRaspberryPiPico2W.examples.fade.name': 'Fade',
            'microPythonRaspberryPiPico2W.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonRaspberryPiPico2W.examples.knob.name': 'Knob',
            'microPythonRaspberryPiPico2W.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonRaspberryPiPico2W.examples.servoSweep.name': 'Servo Sweep',
            'microPythonRaspberryPiPico2W.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonRaspberryPiPico2W.examples.consolePrint.name': 'Console Print',
            'microPythonRaspberryPiPico2W.examples.consolePrint.description': 'Print messages to the terminal.'
        },
        'ru': {
            'microPythonRaspberryPiPico2W.description': 'A wireless variant of the Raspberry Pi Pico 2 powered by the RP2350 with onboard Wi-Fi and Bluetooth.',
            'microPythonRaspberryPiPico2W.examples.blink.name': 'Blink',
            'microPythonRaspberryPiPico2W.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonRaspberryPiPico2W.examples.button.name': 'Button',
            'microPythonRaspberryPiPico2W.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonRaspberryPiPico2W.examples.fade.name': 'Fade',
            'microPythonRaspberryPiPico2W.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonRaspberryPiPico2W.examples.knob.name': 'Knob',
            'microPythonRaspberryPiPico2W.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonRaspberryPiPico2W.examples.servoSweep.name': 'Servo Sweep',
            'microPythonRaspberryPiPico2W.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonRaspberryPiPico2W.examples.consolePrint.name': 'Console Print',
            'microPythonRaspberryPiPico2W.examples.consolePrint.description': 'Print messages to the terminal.'
        },
        'zh-cn': {
            'microPythonRaspberryPiPico2W.description': 'A wireless variant of the Raspberry Pi Pico 2 powered by the RP2350 with onboard Wi-Fi and Bluetooth.',
            'microPythonRaspberryPiPico2W.examples.blink.name': 'Blink',
            'microPythonRaspberryPiPico2W.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonRaspberryPiPico2W.examples.button.name': 'Button',
            'microPythonRaspberryPiPico2W.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonRaspberryPiPico2W.examples.fade.name': 'Fade',
            'microPythonRaspberryPiPico2W.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonRaspberryPiPico2W.examples.knob.name': 'Knob',
            'microPythonRaspberryPiPico2W.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonRaspberryPiPico2W.examples.servoSweep.name': 'Servo Sweep',
            'microPythonRaspberryPiPico2W.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonRaspberryPiPico2W.examples.consolePrint.name': 'Console Print',
            'microPythonRaspberryPiPico2W.examples.consolePrint.description': 'Print messages to the terminal.'
        },
        'zh-tw': {
            'microPythonRaspberryPiPico2W.description': 'A wireless variant of the Raspberry Pi Pico 2 powered by the RP2350 with onboard Wi-Fi and Bluetooth.',
            'microPythonRaspberryPiPico2W.examples.blink.name': 'Blink',
            'microPythonRaspberryPiPico2W.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonRaspberryPiPico2W.examples.button.name': 'Button',
            'microPythonRaspberryPiPico2W.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonRaspberryPiPico2W.examples.fade.name': 'Fade',
            'microPythonRaspberryPiPico2W.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonRaspberryPiPico2W.examples.knob.name': 'Knob',
            'microPythonRaspberryPiPico2W.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonRaspberryPiPico2W.examples.servoSweep.name': 'Servo Sweep',
            'microPythonRaspberryPiPico2W.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonRaspberryPiPico2W.examples.consolePrint.name': 'Console Print',
            'microPythonRaspberryPiPico2W.examples.consolePrint.description': 'Print messages to the terminal.'
        }
    },
    'extensions': {
        'en': {
            'microPythonRaspberryPiPico2W.modeMenu.input': 'input',
            'microPythonRaspberryPiPico2W.modeMenu.output': 'output',
            'microPythonRaspberryPiPico2W.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPico2W.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPico2W.levelMenu.high': 'high',
            'microPythonRaspberryPiPico2W.levelMenu.low': 'low',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPico2W.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPico2W.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPico2W.category.pins': 'Pins',
            'microPythonRaspberryPiPico2W.category.serial': 'Serial',
            'microPythonRaspberryPiPico2W.category.console': 'Console',
            'microPythonRaspberryPiPico2W.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPico2W.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPico2W.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPico2W.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2W.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPico2W.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPico2W.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPico2W.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonRaspberryPiPico2W.modeMenu.input': 'input',
            'microPythonRaspberryPiPico2W.modeMenu.output': 'output',
            'microPythonRaspberryPiPico2W.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPico2W.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPico2W.levelMenu.high': 'high',
            'microPythonRaspberryPiPico2W.levelMenu.low': 'low',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPico2W.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPico2W.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPico2W.category.pins': 'Pins',
            'microPythonRaspberryPiPico2W.category.serial': 'Serial',
            'microPythonRaspberryPiPico2W.category.console': 'Console',
            'microPythonRaspberryPiPico2W.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPico2W.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPico2W.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPico2W.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2W.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPico2W.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPico2W.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPico2W.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonRaspberryPiPico2W.modeMenu.input': 'input',
            'microPythonRaspberryPiPico2W.modeMenu.output': 'output',
            'microPythonRaspberryPiPico2W.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPico2W.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPico2W.levelMenu.high': 'high',
            'microPythonRaspberryPiPico2W.levelMenu.low': 'low',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPico2W.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPico2W.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPico2W.category.pins': 'Pins',
            'microPythonRaspberryPiPico2W.category.serial': 'Serial',
            'microPythonRaspberryPiPico2W.category.console': 'Console',
            'microPythonRaspberryPiPico2W.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPico2W.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPico2W.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPico2W.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2W.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPico2W.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPico2W.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPico2W.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-tw': {
            'microPythonRaspberryPiPico2W.modeMenu.input': 'input',
            'microPythonRaspberryPiPico2W.modeMenu.output': 'output',
            'microPythonRaspberryPiPico2W.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPico2W.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPico2W.levelMenu.high': 'high',
            'microPythonRaspberryPiPico2W.levelMenu.low': 'low',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPico2W.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPico2W.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPico2W.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPico2W.category.pins': 'Pins',
            'microPythonRaspberryPiPico2W.category.serial': 'Serial',
            'microPythonRaspberryPiPico2W.category.console': 'Console',
            'microPythonRaspberryPiPico2W.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPico2W.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPico2W.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPico2W.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2W.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPico2W.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2W.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPico2W.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPico2W.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPico2W.console.consoleInput': 'prompt [TEXT] and read input'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
